name: Deploy to Server

on:
  push:
    branches: [main]

env:
  SERVER_IP: 178.79.191.208

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check commit message
      if: contains(github.event.head_commit.message, 'deploy')
      run: echo "Deploying to server..."

    - name: Set up SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

    - name: Deploy Code
      run: |
        rsync -ahipvz --delete \
        --exclude='.git/' \
        --exclude='*.pyc' \
        --exclude='.idea/' \ 
        --delete-excluded \
        --exclude='__pycache__/' \
        -e "ssh -o StrictHostKeyChecking=no \
        ../ root@${SERVER_IP}:/github/ecom/

    - name: Build Docker Containers
      run: |
        ssh -o StrictHostKeyChecking=no root@${SERVER_IP} \
        "cd /github/ecom && docker compose up --build -d"
