name: Django Tests & Auto Merge

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python manage.py test

    - name: Auto Merge
      if: success()
      uses: actions/bin/filter@v1
      with:
        args: merge
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
